"""Auto migration

Revision ID: c6beb0362a8b
Revises: 57721c5e007b
Create Date: 2025-04-23 08:19:50.504139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6beb0362a8b'
down_revision = '57721c5e007b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor_rating', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor_rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
